import { db } from "./db";
import { cars, services, testimonials } from "@shared/schema";

export async function initializeData() {
  try {
    // Check if data already exists
    const existingCars = await db.select().from(cars).limit(1);
    if (existingCars.length > 0) {
      return; // Data already exists
    }

    // Sample cars with comprehensive details
    await db.insert(cars).values([
      {
        make: "Toyota",
        model: "Camry",
        year: 2020,
        price: "24999",
        mileage: 35000,
        color: "Silver",
        interiorColor: "Black",
        transmission: "Automatic",
        drivetrain: "FWD",
        bodyStyle: "Sedan",
        engine: "2.5L 4-Cylinder",
        trim: "LE",
        fuelType: "Gasoline",
        condition: "used",
        status: "available",
        numberOfSeats: 5,
        numberOfDoors: 4,
        mpgCity: 28,
        mpgHighway: 39,
        safetyRating: "5.0",
        dealerRating: "4.8",
        daysOnMarket: 15,
        vehicleHistory: "Clean",
        financing: true,
        images: ["/api/placeholder/600/400"],
        description: "Well-maintained Toyota Camry with excellent fuel economy",
        vin: "1HGBH41JXMN109186",
        features: ["Backup Camera", "Bluetooth", "Cruise Control", "Lane Assist"],
        createdAt: new Date()
      },
      {
        make: "Honda",
        model: "Civic",
        year: 2019,
        price: "19999",
        mileage: 42000,
        color: "Blue",
        interiorColor: "Gray",
        transmission: "Manual",
        drivetrain: "FWD",
        bodyStyle: "Sedan",
        engine: "1.5L Turbo",
        trim: "Sport",
        fuelType: "Gasoline",
        condition: "used",
        status: "available",
        numberOfSeats: 5,
        numberOfDoors: 4,
        mpgCity: 31,
        mpgHighway: 40,
        safetyRating: "5.0",
        dealerRating: "4.7",
        daysOnMarket: 8,
        vehicleHistory: "Single Owner",
        financing: true,
        images: ["/api/placeholder/600/400"],
        description: "Sporty Honda Civic in excellent condition",
        vin: "2HGFC2F59KH123456",
        features: ["Sunroof", "Navigation", "Heated Seats", "Premium Audio"],
        createdAt: new Date()
      },
      {
        make: "Ford",
        model: "F-150",
        year: 2021,
        price: "32999",
        mileage: 25000,
        color: "Black",
        interiorColor: "Black",
        transmission: "Automatic",
        drivetrain: "4WD",
        bodyStyle: "Truck",
        engine: "3.5L V6 EcoBoost",
        trim: "XLT",
        fuelType: "Gasoline",
        condition: "used",
        status: "available",
        numberOfSeats: 6,
        numberOfDoors: 4,
        mpgCity: 20,
        mpgHighway: 24,
        safetyRating: "4.0",
        dealerRating: "4.9",
        daysOnMarket: 22,
        vehicleHistory: "Clean",
        financing: true,
        images: ["/api/placeholder/600/400"],
        description: "Powerful Ford F-150 pickup truck with excellent capability",
        vin: "1FTEW1EP5MFA12345",
        features: ["4WD", "Towing Package", "Bed Liner", "Backup Camera", "Bluetooth"],
        createdAt: new Date()
      },
      {
        make: "Tesla",
        model: "Model 3",
        year: 2022,
        price: "45999",
        mileage: 15000,
        color: "White",
        interiorColor: "Black",
        transmission: "Automatic",
        drivetrain: "RWD",
        bodyStyle: "Sedan",
        engine: "Electric Motor",
        trim: "Standard Range Plus",
        fuelType: "Electric",
        condition: "used",
        status: "available",
        numberOfSeats: 5,
        numberOfDoors: 4,
        mpgCity: 0,
        mpgHighway: 0,
        safetyRating: "5.0",
        dealerRating: "4.8",
        daysOnMarket: 12,
        vehicleHistory: "Single Owner",
        financing: true,
        images: ["/api/placeholder/600/400"],
        description: "Clean Tesla Model 3 with autopilot features",
        vin: "5YJ3E1EA7KF123456",
        features: ["Autopilot", "Supercharging", "Glass Roof", "Premium Audio"],
        createdAt: new Date()
      },
      {
        make: "Toyota",
        model: "Prius",
        year: 2021,
        price: "28999",
        mileage: 18000,
        color: "Silver",
        interiorColor: "Gray",
        transmission: "CVT",
        drivetrain: "FWD",
        bodyStyle: "Hatchback",
        engine: "1.8L Hybrid",
        trim: "LE",
        fuelType: "Hybrid",
        condition: "used",
        status: "available",
        numberOfSeats: 5,
        numberOfDoors: 4,
        mpgCity: 58,
        mpgHighway: 53,
        safetyRating: "4.5",
        dealerRating: "4.6",
        daysOnMarket: 6,
        vehicleHistory: "Clean",
        financing: true,
        images: ["/api/placeholder/600/400"],
        description: "Fuel-efficient hybrid with excellent reliability",
        vin: "JTDKARFU5M3123456",
        features: ["Hybrid System", "Backup Camera", "Toyota Safety Sense", "Bluetooth"],
        createdAt: new Date()
      },
      {
        make: "BMW",
        model: "X3",
        year: 2022,
        price: "42999",
        mileage: 18000,
        color: "White",
        interiorColor: "Brown",
        transmission: "Automatic",
        drivetrain: "AWD",
        bodyStyle: "SUV",
        engine: "2.0L Turbo",
        trim: "xDrive30i",
        fuelType: "Gasoline",
        condition: "used",
        status: "available",
        numberOfSeats: 5,
        numberOfDoors: 4,
        mpgCity: 23,
        mpgHighway: 29,
        safetyRating: "5.0",
        dealerRating: "4.6",
        daysOnMarket: 5,
        vehicleHistory: "Single Owner",
        financing: true,
        images: ["/api/placeholder/600/400"],
        description: "Luxury BMW X3 with premium features and AWD capability",
        vin: "5UXTY3C09N9P12345",
        features: ["Navigation", "Leather Seats", "Heated Seats", "Sunroof", "Premium Audio", "Lane Assist", "Adaptive Cruise Control"],
        createdAt: new Date()
      },
      {
        make: "Tesla",
        model: "Model 3",
        year: 2023,
        price: "38999",
        mileage: 12000,
        color: "Red",
        interiorColor: "White",
        transmission: "Automatic",
        drivetrain: "RWD",
        bodyStyle: "Sedan",
        engine: "Electric Motor",
        trim: "Standard Range Plus",
        fuelType: "Electric",
        condition: "used",
        status: "available",
        numberOfSeats: 5,
        numberOfDoors: 4,
        mpgCity: 142,
        mpgHighway: 132,
        safetyRating: "5.0",
        dealerRating: "4.8",
        daysOnMarket: 3,
        vehicleHistory: "Clean",
        financing: true,
        images: ["/api/placeholder/600/400"],
        description: "Nearly new Tesla Model 3 with Autopilot and premium connectivity",
        vin: "5YJ3E1EA8PF123456",
        features: ["Autopilot", "Premium Audio", "Navigation", "Heated Seats", "Backup Camera"],
        createdAt: new Date()
      },
      {
        make: "Chevrolet",
        model: "Suburban",
        year: 2020,
        price: "48999",
        mileage: 45000,
        color: "Gray",
        interiorColor: "Black",
        transmission: "Automatic",
        drivetrain: "4WD",
        bodyStyle: "SUV",
        engine: "5.3L V8",
        trim: "LT",
        fuelType: "Gasoline",
        condition: "used",
        status: "available",
        numberOfSeats: 8,
        numberOfDoors: 4,
        mpgCity: 16,
        mpgHighway: 20,
        safetyRating: "4.0",
        dealerRating: "4.7",
        daysOnMarket: 30,
        vehicleHistory: "Multiple Owners",
        financing: true,
        images: ["/api/placeholder/600/400"],
        description: "Spacious Chevrolet Suburban perfect for large families",
        vin: "1GNSKCKC8LR123456",
        features: ["Third Row Seating", "Towing Package", "Backup Camera", "Bluetooth", "Cruise Control"],
        createdAt: new Date()
      }
    ]);

    // Sample services
    await db.insert(services).values([
      {
        name: "Oil Change",
        description: "Complete oil change service with premium oil",
        startingPrice: "49.99",
        category: "Maintenance",
        icon: "wrench",
        features: ["Premium Oil", "Filter Replacement", "Fluid Check"],
        duration: "30 minutes",
        isActive: true
      },
      {
        name: "Brake Service",
        description: "Comprehensive brake inspection and service",
        startingPrice: "199.99",
        category: "Safety",
        icon: "disc",
        features: ["Brake Pad Replacement", "Rotor Inspection", "Brake Fluid"],
        duration: "2 hours",
        isActive: true
      },
      {
        name: "Engine Diagnostic",
        description: "Complete engine diagnostic and analysis",
        startingPrice: "99.99",
        category: "Diagnostic",
        icon: "search",
        features: ["Computer Scan", "Error Code Analysis", "Performance Test"],
        duration: "1 hour",
        isActive: true
      }
    ]);

    // Sample testimonials
    await db.insert(testimonials).values([
      {
        name: "John Smith",
        comment: "Excellent service! Found the perfect car and the staff was very helpful.",
        rating: 5,
        role: "Customer",
        isApproved: true,
        createdAt: new Date()
      },
      {
        name: "Sarah Johnson",
        comment: "Great experience with their repair services. Very professional and affordable.",
        rating: 5,
        role: "Customer",
        isApproved: true,
        createdAt: new Date()
      }
    ]);

    console.log("Sample data initialized successfully");
  } catch (error) {
    console.error("Error initializing sample data:", error);
  }
}